/**
 * Patterns: plain-language themes that synthesize several chart factors into one recognizable
 * story, with the astrology behind each shown on request. Draft text for the approver.
 * Rules (which placements point to each pattern) are in patternRules.ts.
 */

export interface PatternText {
  title: string;
  summary: string;
  /** How it can show up in daily life. */
  shows: string;
  /** What is good in it. */
  gift: string;
  /** Where it can get hard. */
  edge: string;
  /** What tends to help. */
  helps: string;
  notice: [string, string, string];
  question: string;
}

export const PATTERNS: Record<string, PatternText> = {
  guarded_heart: {
    title: 'You guard your feelings until it feels safe',
    summary: 'Deep feeling, slow to show. People get your steadiness long before they get your softness, and trust is something they earn by staying.',
    shows: 'You might be the calm one in a crisis and only feel the full weight of it later, alone. People can read you as composed or self-sufficient when inside you are working hard to stay steady. Asking for comfort may feel harder than giving it, and you may wait until you have already handled something before telling anyone it happened.',
    gift: 'You are dependable under pressure. Your feelings tend to be considered rather than reactive, and once you trust someone your loyalty runs deep and lasts.',
    edge: 'Holding everything in can turn into loneliness, or into a sense that you are only acceptable when you are coping. Others may not know you need them, because you rarely let them see it.',
    helps: 'Small, low-stakes moments of letting someone in: saying how you are before you have solved it. Routines that give feelings a place to land, like writing, walking, or a regular call with one trusted person.',
    notice: ['Saying “I’m fine” before you have checked whether you are', 'Feeling tired after being strong for others', 'Relief when someone notices without you having to ask'],
    question: 'Who in your life has earned a less-finished version of you?',
  },
  deep_waters: {
    title: 'You feel things intensely, all the way down',
    summary: 'Nothing about your emotional life is lukewarm. Small moments land with real force, and surface-level connection leaves you hungry.',
    shows: 'You might sense undercurrents in a room before anyone names them, and small slights can register with real force. Closeness may feel all-or-nothing: you want to know people fully, and you can feel exposed when you are known. When something ends, you may need a long time to let it go.',
    gift: 'Emotional courage. You can remain with hard feelings that other people avoid, and that makes you a powerful presence when someone is in pain or in change.',
    edge: 'Intensity can tip into rumination, jealousy, or bracing for betrayal. You may test people without meaning to, or keep a part of yourself hidden as protection.',
    helps: 'Outlets that can take the full volume: physical movement, art, honest conversation with someone who does not flinch. Naming a feeling early, before it builds, can soften its grip.',
    notice: ['Replaying a conversation long after it ended', 'Sensing what is unsaid in a room', 'Wanting to understand why, not only what'],
    question: 'Which of your strong feelings is asking to be understood, rather than acted on?',
  },
  room_to_breathe: {
    title: 'You need room to be yourself, even in closeness',
    summary: 'Closeness matters to you, and so does air. The moment love starts to feel like a cage, part of you starts looking for the door.',
    shows: 'You might be drawn to people who are unusual, independent, or a little out of reach. When things become too predictable or too tight, you can pull back suddenly, and then wonder why. Friendship may matter as much to you as romance, and you may prefer relationships that keep room for each person’s own life.',
    gift: 'You keep relationships alive. You bring curiosity, honesty, and room for growth, and you can love people without needing to own them.',
    edge: 'Mixed signals, when closeness and freedom both feel urgent. Partners may struggle to know whether you are in or out, and you may struggle to know it too.',
    helps: 'Saying clearly what kind of space you need before you need it. Building freedom into a relationship on purpose, so you do not have to take it by surprise.',
    notice: ['Restlessness when plans are fixed too far ahead', 'Attraction to people who are different from you', 'Feeling closest when you also have your own space'],
    question: 'What would a relationship look like that gave you both closeness and air?',
  },
  idealist_in_love: {
    title: 'You see the best in the people you love',
    summary: 'You fall for who someone could be. That generosity is beautiful, and it can blur the person actually standing in front of you.',
    shows: 'You might fall for potential, or feel a near-spiritual pull toward certain people. Romance, music, and beauty can move you strongly. You may give a great deal and expect little, or overlook signs you would notice in a friend’s relationship.',
    gift: 'Compassion and devotion. You can see the soul in people and help them feel seen. Your love has a generous, forgiving quality.',
    edge: 'Disappointment when someone turns out to be only human, or staying loyal to a picture rather than the person in front of you.',
    helps: 'Letting time show you who someone is. Checking your hopes against what people actually do, and keeping some of your devotion for yourself.',
    notice: ['Falling for who someone could become', 'Feeling deeply moved by music or art about love', 'Finding it hard to see red flags in people you care about'],
    question: 'Who are you loving right now: the person, or the picture?',
  },
  high_bar: {
    title: 'You hold yourself to a very high standard',
    summary: 'There is an inner voice that keeps a tally, and it is rarely satisfied. It built a lot of what you are proud of. It also makes rest feel like something to earn.',
    shows: 'You might find it easier to see what is missing than what is done. Praise may slide off while criticism stays. You may take on responsibility early and feel you have to prove yourself, at work or at home, before you can relax.',
    gift: 'Integrity, persistence, and quality. You finish what you start, and the things you build tend to last. Many people with this pattern grow into their strength later in life.',
    edge: 'Harshness toward yourself, fear of failing, and putting off joy until everything is in order. You may judge yourself more severely than you would ever judge a friend.',
    helps: 'Defining “enough” before you begin. Treating rest as part of the work. Noticing the voice that says you have not done enough, and asking whose voice it is.',
    notice: ['Moving straight to the next task without marking what you finished', 'Hearing feedback as a verdict', 'Feeling most at ease when you are useful'],
    question: 'What would you allow yourself if you already felt you had done enough?',
  },
  caretaker: {
    title: 'You take care of everyone, sometimes before yourself',
    summary: 'Before anyone asks, you have already noticed what they need. Your own needs tend to wait at the back of the line.',
    shows: 'You might be the one people call, the one who remembers, the one who smooths things over. You may feel uneasy when someone near you is upset, and calm only once they are. Your own needs can feel less urgent, or harder to name.',
    gift: 'Warmth, attentiveness, and a talent for making people feel at home. You create safety for others.',
    edge: 'Resentment that builds quietly, exhaustion, or relationships where you give far more than you receive.',
    helps: 'Asking “what do I need?” as often as “what do they need?”. Letting others take care of you, even when it feels awkward. Boundaries framed as care, for you and for them.',
    notice: ['Tracking everyone’s mood in a room', 'Saying yes before checking your own energy', 'Discomfort when someone does something for you'],
    question: 'If you cared for yourself the way you care for others, what would change this week?',
  },
  restless_mind: {
    title: 'Your mind moves fast and wants new input',
    summary: 'Your mind runs ahead, connects dots, and gets bored by repetition. Variety is fuel; finishing is the harder part.',
    shows: 'You might have several projects, tabs, or conversations going at once. Ideas may arrive in flashes. You can talk your way into understanding something, and you may need variety to stay engaged.',
    gift: 'Inventiveness, wit, and quick learning. You can see links between fields and explain things in fresh ways.',
    edge: 'Nervous energy, difficulty finishing, or overthinking at night. Your mind may race ahead of your body’s need for rest.',
    helps: 'Writing ideas down so they can wait. Single-tasking blocks with clear ends. Movement or time outdoors to settle a busy head.',
    notice: ['Starting more than you finish', 'Your best ideas arriving at odd moments', 'Needing to talk to find out what you think'],
    question: 'Which idea deserves more of your sustained attention?',
  },
  go_getter: {
    title: 'You go after what you want, directly',
    summary: 'Waiting is not your natural state. Challenge wakes you up, and you would rather move and adjust than plan forever.',
    shows: 'You might act first and plan later, or feel frustrated by slow processes and indirect people. Physical activity may matter to your mood. You can be the one who gets things moving.',
    gift: 'Courage, initiative, and honesty. You can start what others only talk about, and you tend to stand up for people.',
    edge: 'Impatience, flashes of anger, or burning out by pushing too hard. Others may experience your directness as pressure.',
    helps: 'A physical outlet for energy. A pause between impulse and action for decisions that matter. Choosing which battles are worth your fire.',
    notice: ['Frustration with waiting', 'Feeling better after moving your body', 'Being the one who says what everyone is thinking'],
    question: 'Where is your energy most worth spending right now?',
  },
  quiet_anger: {
    title: 'Anger is hard for you to show',
    summary: 'Frustration builds quietly in you. It rarely arrives as a clean “no”; more often as tiredness, distance, or a resentment you notice later.',
    shows: 'You might keep the peace and only realize later that you were angry. Saying no may feel risky. Your drive can be strong in some areas and stalled in others, as if you need permission to go after what you want.',
    gift: 'Restraint, fairness, and staying power. When you do act, it tends to be considered, and you can work steadily toward long goals.',
    edge: 'Frustration that builds without release, passive resistance, or feeling stuck. Your body may carry tension your words do not.',
    helps: 'Practicing small, clean expressions of disagreement. Physical outlets. Noticing anger early, as information about a boundary.',
    notice: ['Realizing you were annoyed hours after the moment', 'Difficulty saying no', 'Tension in your body when you are holding something back'],
    question: 'What is your frustration trying to protect?',
  },
  meaning_seeker: {
    title: 'You need life to mean something',
    summary: 'A life without a bigger why feels too small for you. Truth, growth, and horizons pull harder than comfort does.',
    shows: 'You might be drawn to travel, study, philosophy, or faith. You can be the optimist in the room, and you may change direction when something stops feeling meaningful.',
    gift: 'Vision, generosity, and faith in what is possible. You can inspire others and help them see further.',
    edge: 'Overpromising, restlessness, or skipping over the practical details that make a dream real.',
    helps: 'Linking big goals to small, regular steps. Finding meaning inside ordinary routines as well as beyond them.',
    notice: ['Restlessness when life feels small', 'Lighting up when you learn something new', 'Saying yes to more than you can carry'],
    question: 'What gives your days a sense of purpose right now?',
  },
  to_be_seen: {
    title: 'You need to be seen for who you really are',
    summary: 'There is a bright, creative core in you that wants an audience. Being overlooked stings in a way you rarely admit.',
    shows: 'You might come alive with an audience, a creative project, or a role where you can lead. Being overlooked can hurt more than you show. You may be very generous with your warmth.',
    gift: 'Warmth, creativity, and the ability to lift a room. You can encourage others to shine too.',
    edge: 'Taking a lack of appreciation personally, or tying your worth to how others respond.',
    helps: 'Creating for the joy of it, not only for the response. Seeking out people who see you clearly, and letting yourself be seen by them.',
    notice: ['Feeling flat when your effort goes unnoticed', 'Coming alive when you get to create or lead', 'Loving to make others feel special'],
    question: 'Where in your life do you get to be fully, visibly yourself?',
  },
  transformer: {
    title: 'You are drawn to depth and reinvention',
    summary: 'You have lived several lives in one. Endings tend to remake you, and polite surface answers do not satisfy you.',
    shows: 'You might be fascinated by psychology, mystery, or what people hide. Big turning points may have marked your life. You can sense power dynamics quickly and may resist anyone trying to control you.',
    gift: 'Resilience and the ability to rebuild. You can face what others avoid, and you often help people through their own crises.',
    edge: 'Control, secrecy, or all-or-nothing choices. You may find it hard to trust, or hold on too tightly when you do.',
    helps: 'Letting change happen in steps rather than all at once. Trust built slowly and on purpose. Using your depth to understand, not to defend.',
    notice: ['Being drawn to what is hidden or taboo', 'Feeling like a different person than you were a few years ago', 'Sensing who has power in a room'],
    question: 'What in your life is ready to end so something truer can begin?',
  },
  security_first: {
    title: 'Security and steadiness come first for you',
    summary: 'Ground first, then growth. A stable base (money, home, body) is what lets the rest of you relax and open.',
    shows: 'You might prefer what is proven to what is new. Comfort, good food, nature, and beautiful objects may soothe you. Big changes can unsettle you even when they are good.',
    gift: 'Reliability, patience, and practical sense. You make things that last and you stay when others drift.',
    edge: 'Stubbornness, staying in what is comfortable after it has stopped fitting, or worrying about money even when there is enough.',
    helps: 'Change in small, tested steps. A clear picture of what “enough” looks like. Time in nature or with your hands to reset.',
    notice: ['Feeling calmer with a plan and a budget', 'Comfort from familiar places and routines', 'Resisting change until it is clearly safe'],
    question: 'What does “secure enough” actually look like for you?',
  },
  slow_trust_love: {
    title: 'Love feels serious to you, and trust takes time',
    summary: 'Love is serious business for you. Commitment comes carefully, and you protect yourself until you are sure it is real.',
    shows: 'You might hold back early in relationships, or feel that love has to be earned. You may be drawn to older or more established partners, or to relationships with clear commitments. Showing affection may come through actions more than words.',
    gift: 'Loyalty, steadiness, and commitment. When you love, you build something that lasts and you show up.',
    edge: 'Fear of rejection, loneliness inside a relationship, or a sense that you are not lovable as you are.',
    helps: 'Letting small affections count. Saying what you feel even when it is not yet certain. Remembering that being cared for is not something you have to earn.',
    notice: ['Holding back until you are sure', 'Showing love by doing things', 'A worry of being too much or not enough'],
    question: 'What would it mean to let love in before you feel ready?',
  },
  mirror_of_others: {
    title: 'You discover yourself through other people',
    summary: 'Other people are your mirror. Partnership is where you learn the most about who you are, sometimes at the cost of what you want.',
    shows: 'You might think best in conversation and feel most alive in partnership. Decisions can be easier with someone to bounce them off. You may adapt to the people around you, sometimes so well that you lose track of your own preferences.',
    gift: 'Diplomacy, fairness, and a talent for partnership. You can see several sides of a situation and help people meet in the middle.',
    edge: 'Losing yourself in others, avoiding conflict, or waiting for someone else to decide.',
    helps: 'Checking in with yourself before you check in with others. Practicing small solo decisions. Choosing partners who want to know what you think.',
    notice: ['Thinking out loud with others', 'Taking on the moods of people you are close to', 'Finding it hard to choose alone'],
    question: 'What do you want, before you ask anyone else?',
  },
  own_person: {
    title: 'You march to your own beat',
    summary: 'Rules that make no sense to you do not hold you for long. Independence is less a preference than a need.',
    shows: 'You might question tradition, prefer to learn by experiment, or feel like an outsider in groups. You may change direction suddenly when something stops feeling true.',
    gift: 'Originality and courage. You see options others miss and you give people permission to be different.',
    edge: 'Feeling disconnected, rebelling for its own sake, or pushing people away to protect your freedom.',
    helps: 'Finding your people: those who share your values, not just your habits. Choosing which rules are worth breaking.',
    notice: ['Discomfort with being told what to do', 'Feeling a little outside the group', 'Excitement about new ideas and systems'],
    question: 'Where does your independence serve you, and where does it isolate you?',
  },
  sponge: {
    title: 'You absorb the moods around you',
    summary: 'Rooms, moods, and people soak into you. You often feel what others feel before they have said a word.',
    shows: 'You might come home from a crowded day drained without knowing why. Art, music, and nature may move you deeply. Boundaries between your feelings and other people’s can blur.',
    gift: 'Empathy, intuition, and imagination. You can sense what is needed and offer compassion that others feel deeply.',
    edge: 'Overwhelm, escapism, or taking on problems that are not yours to carry.',
    helps: 'Regular time alone to reset. Asking, “Is this mine?” when a strong feeling arrives. Creative or spiritual practice as a healthy place for your sensitivity.',
    notice: ['Feeling drained after crowds', 'Picking up on moods before words', 'Needing quiet to know what you feel'],
    question: 'How do you tell your feelings apart from everyone else’s?',
  },
  creative_tension: {
    title: 'Inner tension pushes you to grow',
    summary: 'Parts of your chart pull against each other. It is uncomfortable, and it is also the engine behind much of what you build.',
    shows: 'You might feel that nothing comes easily, or that there is constantly a next problem to solve. You can be driven, restless, and resourceful. Pressure may bring out your best work.',
    gift: 'Resilience and achievement. People with this pattern often build remarkable things because they cannot sit still with what is not working.',
    edge: 'Stress, inner conflict, or difficulty resting even when things are fine.',
    helps: 'Seeing tension as energy rather than failure. Channeling it into a project. Building rest into the same routine that holds your effort.',
    notice: ['Feeling most alive when solving a problem', 'Difficulty switching off', 'Growing most through hard periods'],
    question: 'What is your inner tension trying to build?',
  },
  natural_flow: {
    title: 'Some things come easily to you',
    summary: 'Some things come to you with real ease. Gifts that cost you little are the ones you are most likely to underrate.',
    shows: 'You might do things well without much effort, or find that certain doors open readily. You may take your talents for granted and assume everyone can do what you do.',
    gift: 'Natural ability, grace, and a calm that steadies other people.',
    edge: 'Coasting, or avoiding the challenges that would help your gifts grow further.',
    helps: 'Choosing a challenge on purpose. Treating an easy talent as something worth developing.',
    notice: ['Being told you make things look easy', 'Losing interest when there is no challenge', 'Calm in situations that stress others'],
    question: 'Which of your easy gifts deserves serious attention?',
  },
  head_heart: {
    title: 'What you think and what you feel can pull apart',
    summary: 'What you want and what you need often disagree. Much of your growth comes from letting both have a say.',
    shows: 'You might want one thing and need another: freedom and security, ambition and rest. You may decide with your head and then feel uneasy, or follow your feelings and later doubt yourself.',
    gift: 'Complexity and range. You can understand people on both sides of a divide because you hold both sides yourself.',
    edge: 'Indecision or inner conflict, or feeling that no single choice can satisfy all of you.',
    helps: 'Giving each side a voice before you decide. Looking for the option that serves both, rather than choosing one and silencing the other.',
    notice: ['Second-guessing decisions', 'Wanting two things that seem to conflict', 'Feeling understood by very different people'],
    question: 'What do your head and your heart each want, in their own words?',
  },
  generous_spirit: {
    title: 'You are generous, sometimes to a fault',
    summary: 'Warmth, time, encouragement: you give them freely. Optimism draws people to you, and generosity can stretch you thin.',
    shows: 'You might say yes easily, treat people well, and assume the best. Pleasure, abundance, and good company may matter to you.',
    gift: 'Kindness and faith in people. You make others feel welcome and capable.',
    edge: 'Overcommitting, overspending, or difficulty with limits.',
    helps: 'Generosity with a budget, of money and of time. Letting “no” be part of your kindness.',
    notice: ['Offering help before being asked', 'Saying yes to more than fits your week', 'Seeing the good in people quickly'],
    question: 'Where could a limit make your generosity more sustainable?',
  },
  investigator: {
    title: 'You need to get to the bottom of things',
    summary: 'Convenient answers do not satisfy you. Your mind digs until it hits what is actually true.',
    shows: 'You might research deeply, ask the question no one else asks, or notice inconsistencies right away. Secrets and mysteries may interest you. You can be persuasive and hard to fool.',
    gift: 'Insight and focus. You can solve problems others give up on and see through spin.',
    edge: 'Suspicion, obsessive thinking, or using words as weapons when you feel threatened.',
    helps: 'Letting some questions rest. Using your insight with care, especially when you see something others are not ready to hear.',
    notice: ['Needing to know why', 'Noticing what is left out', 'Thinking about something for days'],
    question: 'Which question do you keep returning to, and why?',
  },
  calling: {
    title: 'Your work and purpose are central to who you are',
    summary: 'Work is not only a job for you. Your sense of self is bound up with building something that matters.',
    shows: 'You might measure a good year by what you achieved, or feel lost when work feels meaningless. Reputation and responsibility can matter to you.',
    gift: 'Ambition, leadership, and a sense of mission. You can make real contributions in your field.',
    edge: 'Overwork, or a sense of self that rises and falls with professional success.',
    helps: 'Defining success in your own terms. Keeping some of your identity outside of work.',
    notice: ['Thinking about work in your free time', 'Feeling restless without a goal', 'Caring how your work is seen'],
    question: 'What would you want your work to have meant, looking back?',
  },
  roots: {
    title: 'Home and family shape you deeply',
    summary: 'Home, family, and where you come from run deep in you, and they shape more of your present than they appear to.',
    shows: 'You might need a home that feels like a sanctuary, or carry strong feelings about family, positive, painful, or both. Your inner life may be rich and private.',
    gift: 'Emotional depth, loyalty, and a gift for creating belonging.',
    edge: 'Old family patterns repeating, or withdrawing when the outside world feels harsh.',
    helps: 'Making your home your own. Looking at family patterns with curiosity, keeping what nourishes you and gently changing what does not.',
    notice: ['Strong reactions to family dynamics', 'Needing a retreat at home', 'Memories that stay vivid'],
    question: 'What from your roots do you want to carry forward, and what to set down?',
  },
  inner_world: {
    title: 'You have a rich, private inner world',
    summary: 'A great deal of your life happens on the inside. Solitude is how you recharge, and some of you is hard to put into words.',
    shows: 'You might feel things you cannot fully explain, have vivid dreams, or need time alone more than others. You can work well behind the scenes.',
    gift: 'Intuition, compassion, and spiritual depth. You understand what people cannot say.',
    edge: 'Hiding, self-doubt, or carrying burdens in silence.',
    helps: 'Protected time alone. A practice for your inner life, such as journaling, meditation, or prayer. Letting one or two people into your private world.',
    notice: ['Needing time alone to feel like yourself', 'Insights that arrive in quiet moments', 'Being more than people see'],
    question: 'What part of your inner life wants to be shared?',
  },
  wise_steady: {
    title: 'You have a steady inner compass',
    summary: 'In the Vedic chart, Jupiter supports your Moon (Gaja Kesari yoga): a classic sign of good judgment and the ability to recover your footing.',
    shows: 'You might find your footing again after setbacks, or be the person others come to for perspective. Learning, teaching, and principles may matter to you.',
    gift: 'Wisdom, optimism, and reputation built on good character.',
    edge: 'Being the counselor for everyone and forgetting to ask for counsel yourself.',
    helps: 'Mentors and teachers of your own. Using your perspective on your own life as generously as you do for others.',
    notice: ['People asking your advice', 'Bouncing back after hard times', 'Valuing principles over convenience'],
    question: 'Who gives you the perspective you give others?',
  },
  self_reliant: {
    title: 'You learned to rely on yourself',
    summary: 'In the Vedic chart, your Moon stands alone (Kemadruma yoga). Tradition reads this as self-reliance, often learned by having to manage alone.',
    shows: 'You might be very capable on your own and slow to ask for help. You may have had to find your own way early on.',
    gift: 'Independence, inner strength, and the ability to carry yourself through hard times.',
    edge: 'Isolation, or a belief that you have to do everything alone.',
    helps: 'Letting support in, even in small ways. Building a few relationships where you are allowed to need things.',
    notice: ['Handling things before telling anyone', 'Discomfort asking for help', 'Pride in your self-sufficiency'],
    question: 'Where would it help to stop doing this alone?',
  },
};
