// Builds src/geo/places.data.ts: towns of 5,000+ people with coordinates and a time zone.
// Sources: all-the-cities (GeoNames data, CC BY 4.0) for places; city-timezones (MIT) for
// time zones, assigned from the nearest listed city in the same country. The app shows the
// chosen zone and lets the person change it, because borders between zones can be wrong.
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
const require = createRequire(import.meta.url);
const cities = require('all-the-cities');
const { cityMapping } = require('city-timezones');

const MIN_POP = 5000;
const R = Math.PI / 180;
const dist = (a, b) => {
  const dLat = (b.lat - a.lat) * R, dLon = (b.lon - a.lon) * R;
  const h = Math.sin(dLat / 2) ** 2 + Math.cos(a.lat * R) * Math.cos(b.lat * R) * Math.sin(dLon / 2) ** 2;
  return 12742 * Math.asin(Math.sqrt(h));
};

const tzByCountry = new Map();
for (const c of cityMapping) {
  if (!c.timezone || !c.iso2) continue;
  const list = tzByCountry.get(c.iso2) ?? [];
  list.push({ lat: c.lat, lon: c.lng, tz: c.timezone, province: c.province });
  tzByCountry.set(c.iso2, list);
}
const allTz = [...tzByCountry.values()].flat();

const zones = [];
const zoneIndex = new Map();
const rows = [];
for (const c of cities) {
  if (c.population < MIN_POP) continue;
  const [lon, lat] = c.loc.coordinates;
  const p = { lat, lon };
  const pool = tzByCountry.get(c.country) ?? allTz;
  let best = null, bestD = Infinity;
  for (const t of pool) { const d = dist(p, t); if (d < bestD) { bestD = d; best = t; } }
  if (!best) continue;
  if (!zoneIndex.has(best.tz)) { zoneIndex.set(best.tz, zones.length); zones.push(best.tz); }
  // US/CA admin codes are readable state/province codes; elsewhere use the nearby listed province.
  const region = ['US', 'CA'].includes(c.country) ? c.adminCode : bestD < 40 ? best.province : '';
  const clean = (s) => (s ?? '').replace(/[|\n]/g, ' ');
  rows.push([clean(c.name), clean(region), c.country, lat.toFixed(3), lon.toFixed(3), zoneIndex.get(best.tz), Math.round(c.population / 1000)].join('|'));
}
rows.sort((a, b) => Number(b.split('|')[6]) - Number(a.split('|')[6]));

const out = `// Generated by scripts/build-places.mjs. Do not edit.
// Place data: GeoNames (CC BY 4.0) via all-the-cities; time zones via city-timezones (MIT).
// Row format: name|region|countryCode|lat|lon|zoneIndex|populationThousands
export const ZONES: string[] = ${JSON.stringify(zones)};
export const PLACES = ${JSON.stringify(rows.join('\n'))};
`;
writeFileSync('src/geo/places.data.ts', out);
console.log(rows.length, 'places,', zones.length, 'zones,', (out.length / 1024).toFixed(0), 'KB');
